#tools
[submodule "laravel/Modules/<nome progetto>"]
	path = laravel/Modules/<nome progetto>
	url = git@github.com:aurmich/module_<nome progetto>_fila5.git
[submodule "laravel/Modules/Xot"]
	path = laravel/Modules/Xot
	url = git@github.com:aurmich/module_xot_fila5.git
[submodule "laravel/Modules/Chart"]
	path = laravel/Modules/Chart
	url = git@github.com:aurmich/module_chart_fila5.git
[submodule "laravel/Modules/Limesurvey"]
	path = laravel/Modules/Limesurvey
	url = git@github.com:aurmich/module_limesurvey_fila5.git
[submodule "laravel/Modules/User"]
	path = laravel/Modules/User
	url = git@github.com:aurmich/module_user_fila5.git
[submodule "laravel/Modules/Notify"]
	path = laravel/Modules/Notify
	url = git@github.com:aurmich/module_notify_fila5.git
[submodule "laravel/Modules/UI"]
	path = laravel/Modules/UI
	url = git@github.com:aurmich/module_ui_fila5.git
[submodule "laravel/Modules/Activity"]
	path = laravel/Modules/Activity
	url = git@github.com:aurmich/module_activity_fila5.git
[submodule "laravel/Modules/Gdpr"]
	path = laravel/Modules/Gdpr
	url = git@github.com:aurmich/module_gdpr_fila5.git
[submodule "laravel/Modules/CloudStorage"]
	path = laravel/Modules/CloudStorage
	url = git@github.com:<nome progetto>-tv/module_cloudstorage_fila5.git
[submodule "laravel/Modules/Lang"]
	path = laravel/Modules/Lang
	url = git@github.com:<nome progetto>-tv/module_lang_fila5.git




[submodule "bashscripts"]
	path = bashscripts
	url = git@github.com:aurmich/bashscripts_fila5.git
[submodule "laravel/Modules/Job"]
	path = laravel/Modules/Job
	url = git@github.com:aurmich/module_job_fila5.git
[submodule "laravel/Modules/Media"]
	path = laravel/Modules/Media
	url = git@github.com:aurmich/module_media_fila5.git
[submodule "laravel/Modules/Setting"]
	path = laravel/Modules/Setting
	url = git@github.com:aurmich/module_setting_fila5.git
[submodule "laravel/Modules/Tenant"]
	path = laravel/Modules/Tenant
	url = git@github.com:aurmich/module_tenant_fila5.git

#Themes
[submodule "laravel/Themes/One"]
	path = laravel/Themes/One
	url = git@github.com:aurmich/theme_one_fila5.git


#packages

#docs


#to order !

